#!/usr/bin/env python

# This verification script file is automatically executed after the SALMON.
# If necessary, this script file can used for the verification of the result.
# The script MUST indicate a "return-code 0", if the calculation is successful.
# If a negative value is returned, it is treated as a test failure.

import sys
import os
import numpy as np

# test rule
reference = {}

reference['Si_k.data'] = [
    # Row, Col, Reference, Tolerance, Info
    [1-1, 2-1, -0.37500, 1e-4, 'kx ik=1'],
    [1-1, 3-1, -0.37500, 0.00001, 'ky ik=1'],
    [1-1, 4-1, -0.37500, 0.00001, 'kz ik=1'],
    [1-1, 5-1, +1.00000, 0.00001, 'kw ik=1'],
    [2-1, 2-1, -0.37500, 0.00001, 'kx ik=2'],
    [2-1, 3-1, -0.37500, 0.00001, 'ky ik=2'],
    [2-1, 4-1, -0.12500, 0.00001, 'kz ik=2'],
    [2-1, 5-1, +1.00000, 0.00001, 'kw ik=2'],
]

reference['Si_eigen.data'] = [
    # Row, Col, Reference, Tolerance, Info
    [15-1, 3-1, +0.12324, 1e-3, 'Eigenenergy k=1 b=15'],
    [16-1, 3-1, +0.14200, 1e-3, 'Eigenenergy k=1 b=16'],
    [17-1, 3-1, +0.14185, 1e-3, 'Eigenenergy k=1 b=17'],
    [18-1, 3-1, +0.14920, 1e-3, 'Eigenenergy k=1 b=18'],
    [15-1, 4-1, +2.00000, 1e-4, 'Occupation k=1 b=15'],
    [16-1, 4-1, +2.00000, 1e-4, 'Occupation k=1 b=16'],
    [17-1, 4-1, +0.00000, 1e-4, 'Occupation k=1 b=17'],
    [18-1, 4-1, +0.00000, 1e-4, 'Occupation k=1 b=18'],
]











message = """[{STATUS}] {INFO}
    {ITEM}[{I:d},{J:d}]: {VAL:+.18e} (ref: {REF:+.18e})
    diff: {DIFF:1.4e} {CMP} tol: {TOL:1.4e}"""

def main():
    print("#" * 60)
    print("# Verification start")

    return_code = 0

    for item, table in reference.items():
        if os.path.isfile(item):
            data = np.loadtxt(item)
            for i, j, ref, tol, info in table:
                diff = np.abs(data[i, j] - ref)
                if diff <= tol:
                    status, cmp = 'Success', '<='
                else:
                    status, cmp = 'Failure', '>'
                    return_code = -1
                    
                print(message.format(
                    STATUS=status, INFO=info, ITEM=item, I=i, J=j, VAL=data[i, j],
                    REF=ref, DIFF=diff, CMP=cmp, TOL=tol
                ))
        else:
            print('[Error] "%s" is not found' % item)

    print("# Verification end")
    print("#" * 60)

    sys.exit(return_code)


if __name__ == "__main__":
    main()
