#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/C_rps.dat ./
cp ../pseudo/H_rps.dat ./
cp ../101_C2H2_gs/C2H2.data ./
if [ -e C2H2-ALP.data ]; then
  rm C2H2-ALP.data
fi
