#!/usr/bin/env python 

# This verification script file is automatically executed after the SALMON. 
# If necessary, this script file can used for the verification of the result. 
# The script MUST indicate a "return-code 0", if the calculation is successful. 
# If a negative value is returned, it is treated as a test failure. 
 
import sys 
import os 
import re 

print("#" * 60) 
print("# Verification start") 

filelist = [ 
    "C2H2-ALP.data", 
] 

checklist = { 
    # Oscillator strength
    "Oscillator Strength (z-direction, 9.28eV)": [
        -100, # Temporary value for result
        1.2082143,  # Reference value 
        0.001,  # Permissible error 
    ], 
} 

print("# Checking the existance of outputfile") 
for item in filelist: 
    if not os.path.exists(item): 
        print("File not found: %s" % item) 
        sys.exit(-1)  # Failure 

print("# Checking calculated result")
result = {}
linecount = 0
for line in open("C2H2-ALP.data"):
    linecount += 1
    if linecount == 930: # corresponds to a line of 9.28eV
        for name, [resval, refval, error] in checklist.items(): 
            data = line.split()
            result[name] = float(data[9])
            print(result[name])

for name, [resval, refval, error] in checklist.items():
    if name not in result: 
        print("Result %s (%s) is not found" % (name, ptn)) 
        sys.exit(-1)  # Failure 
    else:
        print("Result %s = %e (Reference = %e)" % (name, result[name], refval)) 
        if abs(result[name] - refval) > error: 
            print("Mismatch |%e - %e| > %e)" % (result[name], refval, error)) 
            sys.exit(-1)  # Failure 

print("# Verification end") 
print("#" * 60) 

sys.exit(0)  # Success 
