#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/Si_rps.dat ./
if [ -e Si_gs.bin ]; then
  rm Si_gs.bin
fi
