# gnu-without-mpi

TARGET = salmon.cpu
FC = gfortran
CC = gcc
FFLAGS = -O3 -fopenmp -Wall -cpp -ffree-form -ffree-line-length-none
CFLAGS = -O3 -fopenmp -Wall
LIBLAPACK = -llapack -lblas
MODULE_SWITCH = -J
COMM_SET = dummy

include $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/make.body
