#! /bin/bash
#
#   Copyright 2017-2019 SALMON developers
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

export CUDA_VISIBLE_DEVICES=`nvidia-smi -L | awk 'BEGIN { a = 0 } { print a ; a += 1 }' | paste -s -d,`
export CUDA_MPS_PIPE_DIRECTORY=/tmp/${UID}-nvidia-mps
export CUDA_MPS_LOG_DIRECTORY=/tmp/${UID}-nvidia-log
nvidia-cuda-mps-control -d > /dev/null
mps_started=$?

$*

if [ $mps_started -eq 0 ]; then
  echo quit | nvidia-cuda-mps-control
fi
