#! /bin/bash
#
#   Copyright 2017-2019 SALMON developers
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

for((i=0; i<${NSOCKETS_PER_NODE}; i++)); do
  for((j=0; j<${nprocs_per_socket}; j++)); do
    # block distribution
    if [[ ${comm_world_local_rank} -eq $((i * nprocs_per_socket + j)) ]]; then
      export CUDA_VISIBLE_DEVICES=$((i % NGPUS_PER_NODE))
    fi
  done
done

if [[ $# -gt 0 ]]; then
  exec $@
fi
