# fujitsu

SALMON = $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../)

TARGET = $(SALMON)/bin/salmon.cpu
FC = mpifrtpx
CC = mpifccpx
FFLAGS = -O3 -Kfast,openmp,simd=1 -Cpp -Kocl,nooptmsg
CFLAGS = -O3 -Kfast,openmp,simd=1 -Kocl,nooptmsg
FILE_MATHLIB = lapack
LIBLAPACK = -SSL2BLAMP
LIBSCALAPACK = -SCALAPACK -SSL2BLAMP
MODULE_SWITCH = -M
COMM_SET =

include $(SALMON)/gnu_makefiles/make.body
